apiVersion: v1
kind: Secret
metadata:
  name: secret-parameters
data:
  domain: aHR0cHM6Ly9kZXYtYXBpLmNvbXBhbnkuY29t
  apiUrl: L2FwaS92MQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-python
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend 
    spec:
      containers:
        - name: app-python
          image: nginx:alpine
          env:
            - name: DOMAIN
              valueFrom:
                secretKeyRef:
                  name: secret-parameters
                  key: domain
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: secret-parameters
                  key: apiUrl                  