services:
  mysql-server:
    image: mysql:8
    container_name: mysql-server
    profiles:
      - rabbitmq
      - kafka
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appointments_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - net-ms

  mysql-client:
    image: phpmyadmin
    container_name: mysql-client
    ports:
      - "8080:80"
    profiles:
      - rabbitmq
      - kafka
    environment:
      PMA_HOST: mysql-server
      PMA_USER: appuser
      PMA_PASSWORD: apppassword
    networks:
      - net-ms

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"   
    profiles:
      - rabbitmq
    networks:
      - net-ms

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    container_name: zookeeper
    hostname: zookeeper
    restart: unless-stopped
    profiles:
      - kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    healthcheck:
      test: nc -z localhost 2181 || exit 1
      interval: 5s
      timeout: 5s
      retries: 3
      start_interval: 5s
      start_period: 10s
    networks:
      - net-ms

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    restart: unless-stopped
    depends_on:
      zookeeper:
        condition: service_healthy
    profiles:
      - kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    healthcheck:
      test: kafka-topics --bootstrap-server kafka:29092 --list
      interval: 10s
      timeout: 10s
      retries: 15
      start_interval: 10s
      start_period: 40s
    ports:
      - 9092:9092
    networks:
      - net-ms     

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    profiles:
      - kafka
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - 8090:8080
    environment:
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - net-ms           

  ms-discovery:
    image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/discovery
    build:
      context: ./apps/ms-discovery
      dockerfile: Dockerfile
    container_name: ms-discovery
    profiles:
      - kafka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - net-ms        

  ms-appointment:
    image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/appointment
    build:
      context: ./apps/ms-appointment
      dockerfile: Dockerfile
    container_name: ms-appointment
    profiles:
      - kafka
    depends_on:
      ms-discovery:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4010/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - net-ms  

  ms-appointment-co:
    image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/appointment-co
    build:
      context: ./apps/ms-appointment-co
      dockerfile: Dockerfile
    container_name: ms-appointment-co
    profiles:
      - kafka
    depends_on:
      ms-discovery:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4030/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - net-ms        

  ms-appointment-mx:
    image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/appointment-mx
    build:
      context: ./apps/ms-appointment-mx
      dockerfile: Dockerfile
    container_name: ms-appointment-mx
    profiles:
      - kafka
    depends_on:
      ms-discovery:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4040/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - net-ms  

  ms-appointment-pe:
    image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/appointment-pe
    build:
      context: ./apps/ms-appointment-pe
      dockerfile: Dockerfile
    container_name: ms-appointment-pe
    profiles:
      - kafka
    depends_on:
      ms-discovery:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - net-ms

  ms-auth:
    image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/auth
    build:
      context: ./apps/ms-auth
      dockerfile: Dockerfile
    container_name: ms-auth
    profiles:
      - kafka
    depends_on:
      ms-discovery:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4700/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - net-ms            

  ms-user:
    image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/user
    build:
      context: ./apps/ms-user
      dockerfile: Dockerfile
    container_name: ms-user
    profiles:
      - kafka
    depends_on:
      ms-discovery:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4600/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - net-ms            

  ms-gateway:
    image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/gateway
    build:
      context: ./apps/ms-gateway
      dockerfile: Dockerfile
    container_name: ms-gateway
    ports:
      - "4500:4500"
    profiles:
      - kafka
    depends_on:
      ms-discovery:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4500/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - net-ms            

volumes:
  mysql-data:
    name: mysql-data

networks:
  net-ms:
    driver: bridge
