apiVersion: v1
kind: Service
metadata:
  name: svc-frontend
spec:
  type: ClusterIP
  selector:
    env: dev
    app: frontend
  ports:
    - port: 3000
      targetPort: 8080
      protocol: TCP
      name: port-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-python
spec:
  replicas: 5
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend 
    spec:
      containers:
        - name: app-python
          image: python:3.6-alpine
          command: [
            "sh",
            "-c",
            "echo 'Página creada desde Python' > index.html && python -m http.server 8080"
          ]
