apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
  labels:
    env: dev
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-python
  namespace: ns-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend 
    spec:
      containers:
        - name: app-python
          image: python:3.6-alpine
          command: [
            "sh",
            "-c",
            "echo 'Página creada desde Python' > index.html && python -m http.server 8080"
          ]
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-prd
  labels:
    env: prd
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-python
  namespace: ns-prd
spec:
  replicas: 5
  selector:
    matchLabels:
      env: prd
      app: frontend
  template:
    metadata:
      labels:
        env: prd
        app: frontend 
    spec:
      containers:
        - name: app-python
          image: python:3.6-alpine
          command: [
            "sh",
            "-c",
            "echo 'Página creada desde Python' > index.html && python -m http.server 8080"
          ]          